### ISSUE TITLE
Text content did not match in next.js

### ISSUE THREAD

**Issue by mahdisalehian** [ndresx/react-countdown#101]
I have an error when using it in next.js
The error is: Text content did not match. Server: "20" Client: "19"

**Comment by ndresx** [comment]
Could this have something to do with that the countdown already runs, and then there is a mismatch in the timestamp between client and server? In this case, you would probably have to make use of https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning to suppress this warning because I'm not sure if this is a problem of the countdown. 

Alternatively, you could try to set `autoStart` to `false` and start it through the API once it's available on the client.

**Comment by mahdisalehian** [comment]
> Could this have something to do with that the countdown already runs, and then there is a mismatch in the timestamp between client and server? In this case, you would probably have to make use of https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning to suppress this warning because I'm not sure if this is a problem of the countdown.
> 
> Alternatively, you could try to set `autoStart` to `false` and start it through the API once it's available on the client.

Thankyou. I added suppressHydrationWarning={true} to countdown element, and it worked
