### ISSUE TITLE
useState hook and pause() countdown in functional component way

### ISSUE THREAD

**Issue by david2vicente** [ndresx/react-countdown#108]
Hello,

First of all thanks for you useful library!

I'm struggling to achieve some state update with hooks and the Countdown component in a functional component. 

Here is my scenario : i'd like to click on a button to pause the countdown and then display a modal (like a pause screen). There is a button into the modal to "resume" that close it and resume the countdown.. should be simple.. i'm learning React..

Right now, the countdown is not paused after clicking on pause button because of the setProgram state call. How can i make it work?

```
const MyComponent = () => {
  const countDownRefExo = useRef();
  const [program, setProgram] = useState({
    step: 0, // not useful for the example
    date: Date.now() + 5000
  })
  const [isPlaying, setIsPlaying] = useState(true);

  const handlePause = () => {
    setIsPlaying(false);
    countDownRefExo.current.pause();
  }

  const handlePlay = () => {
    setIsPlaying(true);
    countDownRefExo.current.start();
  }

  function PlayScreen() {
    return <>
      <h1>Play screen!</h1>
      <Countdown date={program.date} renderer={(props) => {
        return <h3>{props.formatted.minutes}:{props.formatted.seconds}</h3>
      }} ref={countDownRefExo}/>}
      <button type="button" onClick={handlePause}>
        <FontAwesomeIcon icon="pause" size="1x"/>
      </button>
    </>
  }

  function PauseScreen() {
    return <div className="modal">
      <h1>Random title</h1>
      <button onClick={handlePlay}>Resume</button>
    </div>
  }

  return (
    <div>
        <PlayScreen/>
        {!isPlaying && <PauseScreen/>}
    </div>
  );
};
```

Regards

**Comment by ndresx** [comment]
Hi @david2vicente and thanks for the feedback.

It took me a bit to figure it out 😄, but the problem is that you are using the function `PlayScreen`  as a component instead of a simple render function. The difference, in this case, is that React loses the component's definition (`PlayScreen` is treated as a functional component here) because of the re-render through the state update. So every time the state is updated, the function `PlayScreen` essentially gets newly created, and React doesn't recognize it anymore as the same one as before.

_If it would be declared outside of `MyComponent ` and receives some extra props, it would work this way._

What you can do is to rename `PlayScreen` to, e.g., `renderPlayScreen` (although that's not the problem, but a good practice to avoid such confusions), but then also call it this way. So, instead of

```ts
  return (
    <div>
        <PlayScreen/>
        {!isPlaying && <PauseScreen/>}
    </div>
  );
```
you could do something like this, and it should work as expected. Notice that I did the same with `renderPauseScreen`, although it wouldn't make a big difference here, but still help React in its reconciliation process.
```ts
  return (
    <div>
        {renderPlayScreen()}
        {!isPlaying && renderPauseScreen()}
    </div>
  );
```

I hope this makes sense. Let me know if you need some more clarification on this!

**Comment by david2vicente** [comment]
Hello @ndresx , you are totally right! I was focused on a specific problem without seeing the whole mess i've made around, and it's not related at all with react-countdown. Renaming with function worked and as you suggest, i'll declare outside the two components to have a cleaner file :)

Thanks for your help and your reactivity!!
