### ISSUE TITLE
When OnComplete is called, completed parameter is not updated

### ISSUE THREAD

**Issue by Raphaww** [ndresx/react-countdown#143]
When onComplete callback is called the 'completed' parameter in custom renderer is not updated

```
renderCountdown({ hours, minutes, seconds, completed }) {
    if (completed) {
      // Render a complete state
      return (
        <div className="countdown">
          Available <span>now!</span>
        </div>
      );
    } else {
      // Render a countdown
      return (
        <div className="countdown">
          Available in
          <span className="clock">
            {hours} hours {minutes} minutes {seconds} seconds
          </span>
        </div>
      );
    }
  }

<Countdown
   date={Date.now() + 5000}
   renderer={this.renderCountdown}
   onComplete={() => {
      this.setState({ isAvailable: true });
   }}
/>
```

the problem exist in version: 2.3.2 and react: 16.8.0

https://codesandbox.io/s/musing-raman-51hms

**Comment by ndresx** [comment]
Hi @Raphaww, thanks for the repro. The problem here is that the countdown's `date` prop is getting reset on the rerender caused by `this.setState({ isAvailable: true });`. The `completed` state is, therefore, only `true` for one render cycle and then immediately switches back to `false` again. However, I agree that the way it behaves is not the most expected one, so I'll see what I can do there.

In the meantime, the best would be to store the date so that it stays persistent across rerenders.

https://codesandbox.io/s/epic-haibt-io52e?file=/index.js

**Comment by Raphaww** [comment]
Thanks for the quick reply, the presented solution works for me. The only reason I opened this issue is because in previous versions of this library it worked "as expected" but I understand that many things have changed since then.
