### ISSUE TITLE
Dynamically rendered countdown keeps running even if it is removed from DOM.

### ISSUE THREAD

**Issue by kasyap-007** [ndresx/react-countdown#200]
The dynamically rendered countdown keeps running even if it is removed from DOM.

autoStart is set to false and onTick function is not called when the timer runs in the background.

steps to reproduce (In provided sandbox): 

Hide the countdown 
wait for a few seconds and show it 
Notice the time difference = no of seconds the countdown is hidden

[Sandbox Link](https://codesandbox.io/s/react-countdown-gq5n58?file=/src/components/CountDown.js)

**Comment by ndresx** [comment]
Hi, this doesn't seem to have something to do with the DOM or that the countdown keeps running. In the example, you can see that the `console.log` in `onTick` is not happening when it gets hidden.

The reason for the countdown changing its time and letting us assume that it's still counting in the background is that the `countdownTimer` value remains the same throughout this process. Given that it's an absolute date value in the future, the countdown will pick up this date once it gets shown (mounted/instantiated) again, resulting in less time between the time that has passed since the click and this future date. I hope this makes sense?

**Comment by kasyap-007** [comment]
Yes, It makes sense, adding useEffect to set the date when the countdown is mounted has fixed my issue, 

Sometimes there is a difference of +/-1 second when the countdown is mounted.

```Javascript
// Timer = 45
  useEffect(() => {
    setCountdownTimer(
      dayjs()
        .add(timer * 60 * 1000, "milliseconds")
        .format("YYYY-MM-DDTHH:mm:ss.sssZ") 
    );
  }, [setCountdownTimer, timer]);


      const onMount = (timeDelta) => {
    const { total, seconds, minutes, hours } = timeDelta;
    console.log({ total, hours, minutes, seconds });
  };
```
```
// console

{total: 2699000, hours: 0, minutes: 44, seconds: 59}
total: 2699000
hours: 0
minutes: 44
seconds: 59
```
Any suggestions to fix this?
