### ISSUE TITLE
Inline styling not reflecting.

### ISSUE THREAD

**Issue by karloluis** [ndresx/react-countdown#3]
The following code is presenting the countdown without the stylization.
```
<Countdown className="countdown"
      date={Date.now() + 13000}
      daysInHours
      style={{color: 'red', fontWeight: 'bold',}}
    \>
```

**Comment by ndresx** [comment]
I kept it as lightweight as possible which why additional attributes like `class`, `style`, or others are not supported since the countdown gets rendered in a simple `<span>` tag.

You would either have to wrap it into another container element and apply the styling there or go for the custom `renderer` prop the component is offering you.

In case you still have some good reasons to add it, please let me know!

**Comment by karloluis** [comment]
I wanted to avoid wrapping it. But it works fine, it's just pretty easy to use inline styling inheritance.
