### ISSUE TITLE
Using daysInHours but hours won't go over 24

### ISSUE THREAD

**Issue by Lukereonal** [ndresx/react-countdown#51]
Hey I tried to show countdown for approx 2 days like this for example `42:50:31` but seems like the `hours` part can only show it to 24 so if the `hours` value go past 24 it will fill `days` value

is this expected? since props `daysInHours` supposed to count `days` as `hours`

**Comment by ndresx** [comment]
Hi @Lukereonal, it seems to be working in the sandbox (https://codesandbox.io/s/flamboyant-dirac-vquv9). What props are you passing in?

**Comment by xi1570-krupeshanadkat** [comment]
Nope, it isnt working for me :(

`<Countdown date={new Date(1602588600000)} daysInHours renderer={MiddleComp} />,`

it shows 3 days 6 hours ...

**Comment by xi1570-krupeshanadkat** [comment]
> Hi @Lukereonal, it seems to be working in the sandbox (https://codesandbox.io/s/flamboyant-dirac-vquv9). What props are you passing in?

@ndresx  here is the sandbox link where it shows its not working : https://codesandbox.io/s/react-countdown-days-to-hours-wguzf?file=/src/index.js

I saw your link too.. in your cases there is no renderer, i guess that is causing the issue?

**Comment by ndresx** [comment]
Hi @xi1570-krupeshanadkat, thanks for bringing this up again. I've checked your example and the problem is that not the `formatted` object (which is also part of the [`renderer`](https://github.com/ndresx/react-countdown#renderer) function props) values are used, but the "raw" ones that basically ignore all formatting options.

Here the working example:
https://codesandbox.io/s/react-countdown-days-to-hours-forked-6lcku?file=/src/App.js

Although it's briefly mentioned in the docs, it's not part of the props' representation there yet, will change this, thanks again!

**Comment by xi1570-krupeshanadkat** [comment]
I see, I was missing the `formatted` object wrapping. Really appreciate your quick response with solution. Thanks for helping out :)
