### ISSUE TITLE
Renderer Zero Pad Time does not work with Renderer

### ISSUE THREAD

**Issue by nalzayat** [ndresx/react-countdown#52]
Seconds and Minutes in renderer do not display leading zeros for render when number is less than ten. Please take a look at the following link for clarification:

https://codesandbox.io/embed/modest-payne-ql6po

**Comment by ndresx** [comment]
Hi @nalzayat. The countdown's version used in the linked sandbox is `1.1.0`, current version is `2.1.1`.

The newer version's `renderer` function comes with additional `props` => `props.formatted` => `props.formatted.hours`. In earlier versions, you would have to manually import `zeroPadTime` (the utility function) to format the time based on your needs, since you are using a custom renderer.

https://codesandbox.io/s/autumn-shape-zyfjy
