### ISSUE TITLE
Add toggle function to the API

### ISSUE THREAD

**Issue by papeloto** [ndresx/react-countdown#65]
It would be great is besides the functions `pause()` and `start()` that the counter provides, you could also provide a `toggle()` function. It will be detail of luxury.

**Comment by ndresx** [comment]
Hey! Thanks for your suggestion, but as you have already mentioned, it would be a detail of luxury 💎😄 not everybody might need, especially when the current API already allows you to implement this with a simple `if` condition on your own.

However, if you need any help with it or have any further questions, please let me know.
Otherwise, I would not add it, for now, to keep its core as tight as possible. Thank you!

**Comment by papeloto** [comment]
Hi Martin! Thanks for answering and listening the suggestion.
I find what you said really reasonable. Thanks again and congrats for such
a library!

**Comment by ndresx** [comment]
Thank you! 😊
