### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by Jbarget** [ndresx/react-countdown#76]
Heya, i notice the size of this package went from 1kb to 17kb (mostly because of `lodash.isequal`
![image](https://user-images.githubusercontent.com/11725595/73543432-3d445580-4437-11ea-809b-21282f5e85a2.png)

![image](https://user-images.githubusercontent.com/11725595/73543445-47665400-4437-11ea-9c3c-aed45b9a4c33.png)

im wondering if theres a way to keep the bundle size down by replacing lodash.isequal and moving `prop-types` from `dependencies` to `devDependencies`?

**Comment by ndresx** [comment]
Hi, thank you for your report!

The bundle size has mainly increased because of the package's functionality change. `react-countdown`'s version 2 was only providing a very minimal component/API for displaying "numbers". Version 2.2.0 comes with a fully functional and customizable countdown component and doesn't have anything to do with the original version of this package, even though it's still supporting this legacy version.

However, I will still be looking into optimizing the bundle size by eventually removing the dependencies you have mentioned before, thanks again!

**Comment by ndresx** [comment]
Hey! I've just released a new version `v2.2.1` which gets rid of the `lodash.isequal` dependency as recommended. Thanks again for this insight! 🎉 

![image](https://user-images.githubusercontent.com/27507295/74085734-7bb3c300-4a7c-11ea-8bfe-7d05fbad1002.png)

I'm still not sure how feasible it is to do the same for `prop-types`, but I will keep an eye on this!

**Comment by Jbarget** [comment]
heya, nice, thanks for that!

`prop-types` should be a `devDependency` rather than a `dependency` and they your package would be dependency free!
