### ISSUE TITLE
Feature request: Add years to renderer(props)

### ISSUE THREAD

**Issue by anarchist912** [ndresx/react-countdown#83]
Very simple, actually.

As `years` will not be needed in many use cases, it would be sufficient to make it available in the `props` param of `renderer`

```
const renderCountdown = ({years, days, hours, minutes, seconds, milliseconds}) => return <div>{years}</div>
```

**Comment by ndresx** [comment]
Thanks for your feedback!

It's currently not planned to include this (because of the reason you have already mentioned), but I will be taking a look to implement this so that people can easily include it if needed. For now, you should be able to derive this from the `total` value that should be part of the `renderer`'s `props`.

**Comment by ndresx** [comment]
I'm closing this for now and put it into the backlog to not forget about it. Thanks again though!
