### ISSUE TITLE
how to reload the class component itself after completion of timer in renderer function?

### ISSUE THREAD

**Issue by SK-CSE** [ndresx/react-countdown#99]
currently if i write setState condition inside if complete then it is trying to reload infinitely, throwing error `TypeError: Cannot read property 'setState' of undefined`
```
  renderer({ days, hours, minutes, completed }){
    if(completed){
    this.setState(
      {reload: true}
    )
      return <span/>
    }else{
      return <span>{hours}:{zeroPad(minutes)}</span>;
    }
  }

**Comment by ndresx** [comment]
This is not really related to the other issue because you are trying to call `setState` within React's render cycle (which shouldn't be done).

What you could do instead is to pass a handler function into the countdown's `onComplete` prop where you could then call `setState`; and then it should work!

**Comment by SK-CSE** [comment]
yes i realized that later and used `onComplete` props to `setState`. thanks @ndresx
